# This workflow is to automate Checkmarx SAST scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_URL
#   - CHECKMARX_USER
#   - CHECKMARX_PASSWORD
#   - CHECKMARX_CLIENT_SECRET
#
# The following variables must be inserted below:
#   - <ProjectName>
#
# Update the 'team' field to reflect the team name used in Checkmarx.
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx SAST Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5 #Github Action version
      with:
        project: 00153967_TEST # <-- Insert Checkmarx SAST Project Name
        team: /CxServer
        checkmarx_url: https://9525-103-241-82-75.ngrok.io # To be stored in GitHub Secrets.
        checkmarx_username: Admin@cx # To be stored in GitHub Secrets.
        checkmarx_password: Admin@12345 # To be stored in GitHub Secrets.
        checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C # To be stored in GitHub Secrets.
        break_build: false
        scanners: sast
        params: --checkmarx.exclude-folders="*reso*" --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --cx-flow.filterSeverity --cx-flow.filterCategory  --checkmarx.disable-clubbing=true --logging.level.com.checkmarx.flow.service=DEBUG
   
